#pragma once

#define ERROR_CODE_SUCCESS			0
#define ERROR_CODE_DATA_EXIST		-1
#define ERROR_CODE_SQL_ERROR		-2
#define ERROR_CODE_HTTP_ERROR		-3
#define ERROR_CODE_HTTP_NOT_FOUND	-4
#define ERROR_CODE_INO_NOT_EXIST	-8
#define ERROR_CODE_NO_BACK_END_URI	-10
#define ERROR_CODE_CTRLSN_NOT_FOUND	-11
#define ERROR_CODE_UNAUTHORIZED		-12
#define ERROR_CODE_INVALID_RESPONSE	-13
#define ERROR_CODE_NO_API_CREDENTIAL -14

